### ISSUE TITLE
Conflicts with puppetlabs-git

### ISSUE THREAD

**Issue by whohoho** [cirrax/puppet-borgbackup#5]
Error while evaluating a Function Call, Duplicate declaration: Package[git] is already declared at (file: /etc/puppet/code/environments/production/modules/git/manifes
ts/init.pp, line: 37); cannot redeclare (file: /etc/puppet/code/environments/production/modules/borgbackup/manifests/git.pp, line: 49, column: 3) on node puppetproxy.la
g

**Comment by trefzer** [comment]
If you do not want this module to install git, you can set the parameter borgbackup::git::packages to not include git.
Though you will loose the appropriat automatic dependency but you can use a custom integration module to fix the dependency if necessary.
