### ISSUE TITLE
check_host not working as intended?

### ISSUE THREAD

**Issue by zoh48gz04** [cirrax/puppet-borgbackup#6]
Hi there,

first thanks for this wonderful module.
I'm currently trying to install it in my setup and got a question regarding the check_host option:

The check_hosts functionality is handled in [manifests/repo.pp:86](https://github.com/cirrax/puppet-borgbackup/blob/master/manifests/repo.pp#L86)

And there's also another check in [templates/repo_header.erb](https://github.com/cirrax/puppet-borgbackup/blob/master/templates/repo_header.erb).

Wouldn't it make sense to use the check_host option here as well if it is set?

My backup-host (A Hetzner Storage-Box) has borg only working on port 23. (port 22 is also available but doesn't support borg)
Therefore my borgbackup::repo-target looks like this: "xyz@xyz.your-storagebox.de:23/./backups/%{::hostname}" which results in a BACKUP_HOST of "xyz.your-storagebox.de:23" which doesn't work with the SSH-command to test if online.

My check_host is set to "xyz.your-storagebox.de" so using check_host there would definitely solve my problem. 

Thanks and best regards,
Moe

**Comment by trefzer** [comment]
the to check hosts have a different purpose: the one in repo.pp is to avoid error on the host to backup as long as the backup server is not yet configured or avoid errors if it it not reachable. this is why it sets the dependencies to noop which will then not apply the puppet code. check_host is a ruby/puppet function.

the one in repo_header.erb is part of the shell script used to ensure the host is available before running icinga checks etc. this ensures a correct output in case of host not reacheable.

now to fix your problem.
If you add BACKUP_HOST to borgbackup::repo::env_vars and set the value to '--port 23 storagebox..' then you could overrule the regex to extract the BACKUP_HOST  (line 9) (it wil still be there, but it will be overwritten in one the next lines.

BACKUP_HOST should not be used anywhere else in the script (as far as I see ;)).
Cheers

Benedikt

**Comment by zoh48gz04** [comment]
Hi Benedikt,

thanks for your fast and detailed answer!
I understand the different purposes.
What I was thinking about is: if you use the check_host option, why not use its value for BACKUP_HOST? It'll save an sed-run in these cases. :D
Or do I have missed a constellation where this would cause problems?

Sorry to bother you about this, I was just thinking this would be cleaner.
Now it sounds like a luxury problem to me.

I fixed it by setting BACKUP_HOST in borgbackup::repos_defaults::env_vars simply to "xyz.your-storagebox.de"

Thanks for your help and have a nice remaining weekend!
